services:
  - type: web
    name: app-book-store-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist/app-book-store/browser
    staticPublishPath: dist/app-book-store
    plan: free
